name = "SchwarzOpt"
uuid = "1f373542-8a5c-11ea-12aa-eb13d5ce787b"
authors = ["Jordan Jalving and Sungho Shin", "University of Wisconsin-Madison"]
version = "0.3.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Plasmo = "d3f7391f-f14a-50cc-bbe4-76a32d1bad3c"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"

[extras]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
KaHyPar = "2a6221f6-aa48-11e9-3542-2d9e0ef01880"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Ipopt", "KaHyPar"]
